import { logger } from "../services/loggerService";

const requiredEnvVariables = [
    // Table and Field names for CalendarSyncedToInvites
    "AIRTABLE_TABLE_CALENDAR_SYNCED_TO_INVITES_NAME",
    "AIRTABLE_TABLE_CALENDAR_SYNCED_TO_INVITES_ID",
    "AIRTABLE_VIEW_CALENDAR_SYNCED_TO_INVITES_ID",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_EVENT_RECORD_ID_ID",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_EVENT_RECORD_ID_NAME",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_EVENT_NAME_ID",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_EVENT_NAME_NAME",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_ELIGIBLE_INVITEES_NO_GEO_ID",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_ELIGIBLE_INVITEES_NO_GEO_NAME",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_ELIGIBLE_INVITEES_UNIQUE_CODE_ID",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_ELIGIBLE_INVITEES_UNIQUE_CODE_NAME",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_ATTENDEE_LISTS_ID",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_ATTENDEE_LISTS_NAME",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_CATEGORY_FOR_PORTAL_ID",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_CATEGORY_FOR_PORTAL_NAME",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_CALENDAR_SLOT_ID",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_CALENDAR_SLOT_NAME",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_RSVP_REJECTION_REASONS_ID",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_RSVP_REJECTION_REASONS_NAME",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_DETAIL_LINK_FOR_PORTAL_ID",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_DETAIL_LINK_FOR_PORTAL_NAME",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_LOCATION_ID",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_LOCATION_NAME",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_INCLUDE_IN_PORTAL_ID",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_INCLUDE_IN_PORTAL_NAME",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_EVENT_ORGANIZER_CONTACT_ID",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_EVENT_ORGANIZER_CONTACT_NAME",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_TOPIC_ID",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_TOPIC_NAME",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_ATTENDEE_LIST_FOR_PORTAL_ID",
    "AIRTABLE_FIELD_CALENDAR_SYNCED_TO_INVITES_ATTENDEE_LIST_FOR_PORTAL_NAME",

    // Table and Field names for SplashRSVPTracker
    "AIRTABLE_TABLE_SPLASH_RSVP_TRACKER_NAME",
    "AIRTABLE_TABLE_SPLASH_RSVP_TRACKER_ID",
    "AIRTABLE_VIEW_SPLASH_RSVP_TRACKER_ID",
    "AIRTABLE_FIELD_SPLASH_RSVP_TRACKER_EVENT_RECORD_ID_ID",
    "AIRTABLE_FIELD_SPLASH_RSVP_TRACKER_EVENT_RECORD_ID_NAME",
    "AIRTABLE_FIELD_SPLASH_RSVP_TRACKER_MEMBER_RECORD_ID",
    "AIRTABLE_FIELD_SPLASH_RSVP_TRACKER_MEMBER_RECORD_NAME",
    "AIRTABLE_FIELD_SPLASH_RSVP_TRACKER_MEMBER_RECORD_ID_ID",
    "AIRTABLE_FIELD_SPLASH_RSVP_TRACKER_MEMBER_RECORD_ID_NAME",
    "AIRTABLE_FIELD_SPLASH_RSVP_TRACKER_EVENT_MEMBER_RECORD_ID",
    "AIRTABLE_FIELD_SPLASH_RSVP_TRACKER_EVENT_MEMBER_RECORD_NAME",
    "AIRTABLE_FIELD_SPLASH_RSVP_TRACKER_RSVP_STATUS_ID",
    "AIRTABLE_FIELD_SPLASH_RSVP_TRACKER_RSVP_STATUS_NAME",
    "AIRTABLE_FIELD_SPLASH_RSVP_TRACKER_RSVP_DATE_ID",
    "AIRTABLE_FIELD_SPLASH_RSVP_TRACKER_RSVP_DATE_NAME",
    "AIRTABLE_FIELD_SPLASH_RSVP_TRACKER_UPDATED_ID",
    "AIRTABLE_FIELD_SPLASH_RSVP_TRACKER_UPDATED_NAME",
    "AIRTABLE_FIELD_SPLASH_RSVP_TRACKER_MEMBER_NAME_ID",
    "AIRTABLE_FIELD_SPLASH_RSVP_TRACKER_MEMBER_NAME_NAME",
    "AIRTABLE_FIELD_SPLASH_RSVP_TRACKER_MEMBER_TITLE_ID",
    "AIRTABLE_FIELD_SPLASH_RSVP_TRACKER_MEMBER_TITLE_NAME",
    "AIRTABLE_FIELD_SPLASH_RSVP_TRACKER_MEMBER_COMPANY_ID",
    "AIRTABLE_FIELD_SPLASH_RSVP_TRACKER_MEMBER_COMPANY_NAME",
    "AIRTABLE_FIELD_SPLASH_RSVP_TRACKER_MEMBER_UNIQUE_CODE_ID",
    "AIRTABLE_FIELD_SPLASH_RSVP_TRACKER_MEMBER_UNIQUE_CODE_NAME",

    // Table and Field names for RSVP Tracker
    "AIRTABLE_TABLE_RSVP_TRACKER_NAME",
    "AIRTABLE_TABLE_RSVP_TRACKER_ID",
    "AIRTABLE_FIELD_RSVP_TRACKER_EVENT_ID_ID",
    "AIRTABLE_FIELD_RSVP_TRACKER_EVENT_ID_NAME",
    "AIRTABLE_FIELD_RSVP_TRACKER_EVENT_RECORD_ID_ID",
    "AIRTABLE_FIELD_RSVP_TRACKER_EVENT_RECORD_ID_NAME",
    "AIRTABLE_FIELD_RSVP_TRACKER_MEMBER_CODE_ID",
    "AIRTABLE_FIELD_RSVP_TRACKER_MEMBER_CODE_NAME",
    "AIRTABLE_FIELD_RSVP_TRACKER_MEMBER_RECORD_ID",
    "AIRTABLE_FIELD_RSVP_TRACKER_MEMBER_RECORD_NAME",
    "AIRTABLE_FIELD_RSVP_TRACKER_EVENT_MEMBER_RECORD_ID_ID",
    "AIRTABLE_FIELD_RSVP_TRACKER_EVENT_MEMBER_RECORD_ID_NAME",
    "AIRTABLE_FIELD_RSVP_TRACKER_RSVP_STATUS_ID",
    "AIRTABLE_FIELD_RSVP_TRACKER_RSVP_STATUS_NAME",
    "AIRTABLE_FIELD_RSVP_TRACKER_RSVP_DATE_ID",
    "AIRTABLE_FIELD_RSVP_TRACKER_RSVP_DATE_NAME",
    "AIRTABLE_FIELD_RSVP_TRACKER_CREATED_ID",
    "AIRTABLE_FIELD_RSVP_TRACKER_CREATED_NAME",
    "AIRTABLE_FIELD_RSVP_TRACKER_SOURCE_ID",
    "AIRTABLE_FIELD_RSVP_TRACKER_SOURCE_NAME",
    "AIRTABLE_FIELD_RSVP_TRACKER_NO_REASONS_ID",
    "AIRTABLE_FIELD_RSVP_TRACKER_NO_REASONS_NAME",

    // Table and Field names for Members
    "AIRTABLE_TABLE_MEMBERS_NAME",
    "AIRTABLE_TABLE_MEMBERS_ID",
    "AIRTABLE_FIELD_MEMBERS_UNIQUE_CODE_ID",
    "AIRTABLE_FIELD_MEMBERS_UNIQUE_CODE_NAME",
    "AIRTABLE_FIELD_MEMBERS_FIRST_NAME_ID",
    "AIRTABLE_FIELD_MEMBERS_FIRST_NAME_NAME",
    "AIRTABLE_FIELD_MEMBERS_LAST_NAME_ID",
    "AIRTABLE_FIELD_MEMBERS_LAST_NAME_NAME",
    "AIRTABLE_FIELD_MEMBERS_TITLE_ID",
    "AIRTABLE_FIELD_MEMBERS_TITLE_NAME",
    "AIRTABLE_FIELD_MEMBERS_COMPANY_ID",
    "AIRTABLE_FIELD_MEMBERS_COMPANY_NAME",

    // Table and Field names for Opt In Questions
    "AIRTABLE_TABLE_OPT_IN_QUESTIONS_NAME",
    "AIRTABLE_TABLE_OPT_IN_QUESTIONS_ID",
    "AIRTABLE_FIELD_OPT_IN_QUESTIONS_NAME_ID",
    "AIRTABLE_FIELD_OPT_IN_QUESTIONS_NAME_NAME",
    "AIRTABLE_FIELD_OPT_IN_QUESTIONS_TYPE_ID",
    "AIRTABLE_FIELD_OPT_IN_QUESTIONS_TYPE_NAME",
    "AIRTABLE_FIELD_OPT_IN_QUESTIONS_ANSWER_CHOICES_ID",
    "AIRTABLE_FIELD_OPT_IN_QUESTIONS_ANSWER_CHOICES_NAME",
];

export default function validateEnvironment() {
    // Check if all required environment variables are set
    logger.info("Checking for required environment variables");

    const missingEnvVariables = requiredEnvVariables.filter(
        (envVar) => !process.env[envVar]
    );

    if (missingEnvVariables.length > 0) {
        logger.error(
            `Missing environment variables: ${missingEnvVariables.join(", ")}`
        );
        process.exit(1); // Exit the process with an error code
    }

    logger.info("All required environment variables are set");
}
